// Generated by scripts/generate-simple-client.mjs. Edit the JSON Schema source.
package com.yepanywhere.mobile.experimental

import org.json.JSONArray
import org.json.JSONObject

typealias Id = String

typealias Timestamp = String

enum class ActivityState(val wire: String) {
    IDLE("idle"),
    WORKING("working"),
    WAITING("waiting"),
    UNKNOWN("unknown")
}

enum class IssueCoverage(val wire: String) {
    COMPLETE("complete"),
    PARTIAL("partial"),
    DISABLED("disabled"),
    UNSUPPORTED("unsupported"),
    UNAVAILABLE("unavailable")
}

data class IssueRef(
    val id: Id,
    val key: String,
    val provider: String,
    val kind: String,
    val title: String?,
    val url: String?,
)

data class ProjectSummary(
    val id: Id,
    val name: String,
)

data class SessionSummary(
    val id: Id,
    val projectId: Id?,
    val title: String,
    val provider: String,
    val activity: ActivityState,
    val preview: String?,
    val updatedAt: Timestamp?,
    val pendingRequestCount: Int,
    val issues: List<IssueRef>,
    val issueCoverage: IssueCoverage,
)

enum class OverviewLimit(val wire: String) {
    SESSIONS("sessions"),
    PROJECTS("projects"),
    BYTES("bytes"),
    UNAVAILABLE("unavailable")
}

data class OverviewCoverage(
    val complete: Boolean,
    val limitedBy: List<OverviewLimit>,
)

data class SourceOverview(
    val kind: String,
    val displayName: String,
    val projects: List<ProjectSummary>,
    val sessions: List<SessionSummary>,
    val coverage: OverviewCoverage,
) : SnapshotView

enum class TextFormat(val wire: String) {
    PLAIN("plain"),
    MARKDOWN("markdown")
}

data class TextContent(
    val kind: String,
    val format: TextFormat,
    val text: String,
) : Content

data class ActivityContent(
    val kind: String,
    val summary: String,
    val toolCount: Int,
    val failedToolCount: Int,
) : Content

data class FailureContent(
    val kind: String,
    val toolName: String,
    val message: String,
    val exitCode: Int?,
) : Content

enum class MediaAvailability(val wire: String) {
    AVAILABLE("available"),
    UNAVAILABLE("unavailable")
}

data class MediaContent(
    val kind: String,
    val mediaId: Id,
    val description: String,
    val availability: MediaAvailability,
) : Content

sealed interface Content {
    data class Unknown(val originalKind: String, val raw: JSONObject) : Content
}

enum class MessageRole(val wire: String) {
    USER("user"),
    AGENT("agent")
}

enum class MessageState(val wire: String) {
    COMPLETE("complete"),
    GROWING("growing"),
    INTERRUPTED("interrupted")
}

data class ConversationMessage(
    val id: Id,
    val role: MessageRole,
    val createdAt: Timestamp?,
    val state: MessageState,
    val truncated: Boolean,
    val content: List<Content>,
)

data class QuestionRequest(
    val kind: String,
    val id: Id,
    val prompt: String,
    val options: List<String>,
    val canAnswer: Boolean,
) : PendingRequest

sealed interface PendingRequest {
    data class Unknown(val originalKind: String, val raw: JSONObject) : PendingRequest
}

enum class Knowledge(val wire: String) {
    YES("yes"),
    NO("no"),
    UNKNOWN("unknown")
}

enum class HistoryLimit(val wire: String) {
    MAX_MESSAGES("maxMessages"),
    COMPACTION_SCOPE("compactionScope"),
    BYTES("bytes"),
    UNAVAILABLE("unavailable")
}

data class HistoryCoverage(
    val scope: String,
    val compactions: Int,
    val maxMessages: Int,
    val returnedMessages: Int,
    val earlierInScope: Boolean,
    val earlierOutsideScope: Knowledge,
    val completeForRequest: Boolean,
    val limitedBy: List<HistoryLimit>,
    val anchorMessageId: Id?,
)

data class Conversation(
    val kind: String,
    val sessionId: Id,
    val activity: ActivityState,
    val messages: List<ConversationMessage>,
    val pendingRequests: List<PendingRequest>,
    val coverage: HistoryCoverage,
) : SnapshotView

enum class ErrorCode(val wire: String) {
    REVISION_MISMATCH("revisionMismatch"),
    UNAVAILABLE("unavailable"),
    NOT_FOUND("notFound"),
    ANCHOR_UNAVAILABLE("anchorUnavailable"),
    INVALID_REQUEST("invalidRequest")
}

data class ApiError(
    val kind: String,
    val code: ErrorCode,
    val message: String,
) : SnapshotView

sealed interface SnapshotView {
    data class Unknown(val originalKind: String, val raw: JSONObject) : SnapshotView
}

data class SnapshotEnvelope(
    val apiRevision: String,
    val subscriptionId: Id,
    val sequence: Int,
    val view: SnapshotView,
)

data class ConversationQuery(
    val sessionId: Id,
    val maxMessages: Int,
    val anchorMessageId: Id?,
)

object SimpleClientContract {
    const val MAX_SNAPSHOT_BYTES = 262144
    fun decodeSnapshot(encoded: String): SnapshotEnvelope {
        require(encoded.toByteArray(Charsets.UTF_8).size <= MAX_SNAPSHOT_BYTES) { "Snapshot byte limit exceeded" }
        return decodeSnapshotEnvelope(JSONObject(encoded))
    }
    private fun objectValue(value: Any): JSONObject = value as? JSONObject ?: error("Expected object")
    private fun field(obj: JSONObject, name: String): Any {
        require(obj.has(name)) { "Missing field: $name" }
        return obj.get(name)
    }
    private fun stringValue(value: Any, min: Int, max: Int): String {
        require(value is String) { "Expected string" }
        require(value.codePointCount(0, value.length) in min..max) { "String length out of bounds" }
        return value
    }
    private fun intValue(value: Any, min: Int, max: Int): Int {
        require(value is Number) { "Expected number" }
        val number = value.toDouble()
        require(number.isFinite() && number >= min && number <= max && number % 1.0 == 0.0) { "Invalid integer" }
        return number.toInt()
    }
    private fun booleanValue(value: Any): Boolean {
        require(value is Boolean) { "Expected boolean" }
        return value
    }
    private fun arrayValue(value: Any, min: Int, max: Int): List<Any> {
        require(value is JSONArray && value.length() in min..max) { "Invalid array" }
        return List(value.length()) { value.get(it) }
    }

    fun decodeId(value: Any): Id {
        return stringValue(value, 1, 256)
    }

    fun decodeTimestamp(value: Any): Timestamp {
        return stringValue(value, 24, 24).also { require(Regex("^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}\\.\\d{3}Z$").matches(it)) { "Invalid string format" } }
    }

    fun decodeActivityState(value: Any): ActivityState {
        val wire = value as? String ?: error("Expected enum string")
        return ActivityState.entries.firstOrNull { it.wire == wire } ?: error("Unknown ActivityState")
    }

    fun decodeIssueCoverage(value: Any): IssueCoverage {
        val wire = value as? String ?: error("Expected enum string")
        return IssueCoverage.entries.firstOrNull { it.wire == wire } ?: error("Unknown IssueCoverage")
    }

    fun decodeIssueRef(value: Any): IssueRef {
        val obj = objectValue(value)
        return IssueRef(
            id = decodeId(field(obj, "id")),
            key = stringValue(field(obj, "key"), 1, 256),
            provider = stringValue(field(obj, "provider"), 1, 64),
            kind = stringValue(field(obj, "kind"), 1, 64),
            title = field(obj, "title").let { if (it == JSONObject.NULL) null else stringValue(it, 1, 512) },
            url = field(obj, "url").let { if (it == JSONObject.NULL) null else stringValue(it, 1, 2048) },
        )
    }

    fun decodeProjectSummary(value: Any): ProjectSummary {
        val obj = objectValue(value)
        return ProjectSummary(
            id = decodeId(field(obj, "id")),
            name = stringValue(field(obj, "name"), 1, 512),
        )
    }

    fun decodeSessionSummary(value: Any): SessionSummary {
        val obj = objectValue(value)
        return SessionSummary(
            id = decodeId(field(obj, "id")),
            projectId = field(obj, "projectId").let { if (it == JSONObject.NULL) null else decodeId(it) },
            title = stringValue(field(obj, "title"), 1, 512),
            provider = stringValue(field(obj, "provider"), 1, 64),
            activity = decodeActivityState(field(obj, "activity")),
            preview = field(obj, "preview").let { if (it == JSONObject.NULL) null else stringValue(it, 1, 1024) },
            updatedAt = field(obj, "updatedAt").let { if (it == JSONObject.NULL) null else decodeTimestamp(it) },
            pendingRequestCount = intValue(field(obj, "pendingRequestCount"), 0, 1000000),
            issues = arrayValue(field(obj, "issues"), 0, 16).map { decodeIssueRef(it) },
            issueCoverage = decodeIssueCoverage(field(obj, "issueCoverage")),
        )
    }

    fun decodeOverviewLimit(value: Any): OverviewLimit {
        val wire = value as? String ?: error("Expected enum string")
        return OverviewLimit.entries.firstOrNull { it.wire == wire } ?: error("Unknown OverviewLimit")
    }

    fun decodeOverviewCoverage(value: Any): OverviewCoverage {
        val obj = objectValue(value)
        return OverviewCoverage(
            complete = booleanValue(field(obj, "complete")),
            limitedBy = arrayValue(field(obj, "limitedBy"), 0, 4).map { decodeOverviewLimit(it) },
        )
    }

    fun decodeSourceOverview(value: Any): SourceOverview {
        val obj = objectValue(value)
        return SourceOverview(
            kind = stringValue(field(obj, "kind"), 0, 1000).also { require(it == "overview") { "Unexpected constant" } },
            displayName = stringValue(field(obj, "displayName"), 1, 512),
            projects = arrayValue(field(obj, "projects"), 0, 100).map { decodeProjectSummary(it) },
            sessions = arrayValue(field(obj, "sessions"), 0, 200).map { decodeSessionSummary(it) },
            coverage = decodeOverviewCoverage(field(obj, "coverage")),
        )
    }

    fun decodeTextFormat(value: Any): TextFormat {
        val wire = value as? String ?: error("Expected enum string")
        return TextFormat.entries.firstOrNull { it.wire == wire } ?: error("Unknown TextFormat")
    }

    fun decodeTextContent(value: Any): TextContent {
        val obj = objectValue(value)
        return TextContent(
            kind = stringValue(field(obj, "kind"), 0, 1000).also { require(it == "text") { "Unexpected constant" } },
            format = decodeTextFormat(field(obj, "format")),
            text = stringValue(field(obj, "text"), 0, 16000),
        )
    }

    fun decodeActivityContent(value: Any): ActivityContent {
        val obj = objectValue(value)
        return ActivityContent(
            kind = stringValue(field(obj, "kind"), 0, 1000).also { require(it == "activity") { "Unexpected constant" } },
            summary = stringValue(field(obj, "summary"), 1, 512),
            toolCount = intValue(field(obj, "toolCount"), 0, 1000000),
            failedToolCount = intValue(field(obj, "failedToolCount"), 0, 1000000),
        )
    }

    fun decodeFailureContent(value: Any): FailureContent {
        val obj = objectValue(value)
        return FailureContent(
            kind = stringValue(field(obj, "kind"), 0, 1000).also { require(it == "failure") { "Unexpected constant" } },
            toolName = stringValue(field(obj, "toolName"), 1, 128),
            message = stringValue(field(obj, "message"), 1, 2048),
            exitCode = field(obj, "exitCode").let { if (it == JSONObject.NULL) null else intValue(it, -2147483648, 2147483647) },
        )
    }

    fun decodeMediaAvailability(value: Any): MediaAvailability {
        val wire = value as? String ?: error("Expected enum string")
        return MediaAvailability.entries.firstOrNull { it.wire == wire } ?: error("Unknown MediaAvailability")
    }

    fun decodeMediaContent(value: Any): MediaContent {
        val obj = objectValue(value)
        return MediaContent(
            kind = stringValue(field(obj, "kind"), 0, 1000).also { require(it == "media") { "Unexpected constant" } },
            mediaId = decodeId(field(obj, "mediaId")),
            description = stringValue(field(obj, "description"), 0, 512),
            availability = decodeMediaAvailability(field(obj, "availability")),
        )
    }

    fun decodeContent(value: Any): Content {
        val obj = objectValue(value)
        return when (val kind = stringValue(field(obj, "kind"), 1, 128)) {
            "text" -> decodeTextContent(obj)
            "activity" -> decodeActivityContent(obj)
            "failure" -> decodeFailureContent(obj)
            "media" -> decodeMediaContent(obj)
            else -> Content.Unknown(kind, JSONObject(obj.toString()))
        }
    }

    fun decodeMessageRole(value: Any): MessageRole {
        val wire = value as? String ?: error("Expected enum string")
        return MessageRole.entries.firstOrNull { it.wire == wire } ?: error("Unknown MessageRole")
    }

    fun decodeMessageState(value: Any): MessageState {
        val wire = value as? String ?: error("Expected enum string")
        return MessageState.entries.firstOrNull { it.wire == wire } ?: error("Unknown MessageState")
    }

    fun decodeConversationMessage(value: Any): ConversationMessage {
        val obj = objectValue(value)
        return ConversationMessage(
            id = decodeId(field(obj, "id")),
            role = decodeMessageRole(field(obj, "role")),
            createdAt = field(obj, "createdAt").let { if (it == JSONObject.NULL) null else decodeTimestamp(it) },
            state = decodeMessageState(field(obj, "state")),
            truncated = booleanValue(field(obj, "truncated")),
            content = arrayValue(field(obj, "content"), 1, 64).map { decodeContent(it) },
        )
    }

    fun decodeQuestionRequest(value: Any): QuestionRequest {
        val obj = objectValue(value)
        return QuestionRequest(
            kind = stringValue(field(obj, "kind"), 0, 1000).also { require(it == "question") { "Unexpected constant" } },
            id = decodeId(field(obj, "id")),
            prompt = stringValue(field(obj, "prompt"), 1, 2048),
            options = arrayValue(field(obj, "options"), 0, 20).map { stringValue(it, 1, 512) },
            canAnswer = booleanValue(field(obj, "canAnswer")).also { require(it == false) { "Unexpected constant" } },
        )
    }

    fun decodePendingRequest(value: Any): PendingRequest {
        val obj = objectValue(value)
        return when (val kind = stringValue(field(obj, "kind"), 1, 128)) {
            "question" -> decodeQuestionRequest(obj)
            else -> PendingRequest.Unknown(kind, JSONObject(obj.toString()))
        }
    }

    fun decodeKnowledge(value: Any): Knowledge {
        val wire = value as? String ?: error("Expected enum string")
        return Knowledge.entries.firstOrNull { it.wire == wire } ?: error("Unknown Knowledge")
    }

    fun decodeHistoryLimit(value: Any): HistoryLimit {
        val wire = value as? String ?: error("Expected enum string")
        return HistoryLimit.entries.firstOrNull { it.wire == wire } ?: error("Unknown HistoryLimit")
    }

    fun decodeHistoryCoverage(value: Any): HistoryCoverage {
        val obj = objectValue(value)
        return HistoryCoverage(
            scope = stringValue(field(obj, "scope"), 0, 1000).also { require(it == "recentCompactions") { "Unexpected constant" } },
            compactions = intValue(field(obj, "compactions"), -2147483648, 2147483647).also { require(it == 2) { "Unexpected constant" } },
            maxMessages = intValue(field(obj, "maxMessages"), 1, 100),
            returnedMessages = intValue(field(obj, "returnedMessages"), 0, 100),
            earlierInScope = booleanValue(field(obj, "earlierInScope")),
            earlierOutsideScope = decodeKnowledge(field(obj, "earlierOutsideScope")),
            completeForRequest = booleanValue(field(obj, "completeForRequest")),
            limitedBy = arrayValue(field(obj, "limitedBy"), 0, 4).map { decodeHistoryLimit(it) },
            anchorMessageId = field(obj, "anchorMessageId").let { if (it == JSONObject.NULL) null else decodeId(it) },
        )
    }

    fun decodeConversation(value: Any): Conversation {
        val obj = objectValue(value)
        return Conversation(
            kind = stringValue(field(obj, "kind"), 0, 1000).also { require(it == "conversation") { "Unexpected constant" } },
            sessionId = decodeId(field(obj, "sessionId")),
            activity = decodeActivityState(field(obj, "activity")),
            messages = arrayValue(field(obj, "messages"), 0, 100).map { decodeConversationMessage(it) },
            pendingRequests = arrayValue(field(obj, "pendingRequests"), 0, 16).map { decodePendingRequest(it) },
            coverage = decodeHistoryCoverage(field(obj, "coverage")),
        )
    }

    fun decodeErrorCode(value: Any): ErrorCode {
        val wire = value as? String ?: error("Expected enum string")
        return ErrorCode.entries.firstOrNull { it.wire == wire } ?: error("Unknown ErrorCode")
    }

    fun decodeApiError(value: Any): ApiError {
        val obj = objectValue(value)
        return ApiError(
            kind = stringValue(field(obj, "kind"), 0, 1000).also { require(it == "error") { "Unexpected constant" } },
            code = decodeErrorCode(field(obj, "code")),
            message = stringValue(field(obj, "message"), 1, 2048),
        )
    }

    fun decodeSnapshotView(value: Any): SnapshotView {
        val obj = objectValue(value)
        return when (val kind = stringValue(field(obj, "kind"), 1, 128)) {
            "overview" -> decodeSourceOverview(obj)
            "conversation" -> decodeConversation(obj)
            "error" -> decodeApiError(obj)
            else -> SnapshotView.Unknown(kind, JSONObject(obj.toString()))
        }
    }

    fun decodeSnapshotEnvelope(value: Any): SnapshotEnvelope {
        val obj = objectValue(value)
        return SnapshotEnvelope(
            apiRevision = stringValue(field(obj, "apiRevision"), 0, 1000).also { require(it == "simple-client-spike-1") { "Unexpected constant" } },
            subscriptionId = decodeId(field(obj, "subscriptionId")),
            sequence = intValue(field(obj, "sequence"), 0, 2147483647),
            view = decodeSnapshotView(field(obj, "view")),
        )
    }

    fun decodeConversationQuery(value: Any): ConversationQuery {
        val obj = objectValue(value)
        return ConversationQuery(
            sessionId = decodeId(field(obj, "sessionId")),
            maxMessages = intValue(field(obj, "maxMessages"), 1, 100),
            anchorMessageId = field(obj, "anchorMessageId").let { if (it == JSONObject.NULL) null else decodeId(it) },
        )
    }
}
